#
# SPDX-License-Identifier: Apache-2.0
#

name: PDO CI with SW supply chain metadata
on: [pull_request, push]
jobs:
    pdo_ci:
        if: "!contains(github.event.commits[0].message, '[skip ci]')"
        name: PDO CI Job
        runs-on: ubuntu-20.04

        strategy:
            matrix:
                interpreter: [wawaka, wawaka-opt]
                pdo_ledger_type: [ccf]

        steps:
            - name: Check out repo
              uses: actions/checkout@v2

            - name: Build and run tests
              env:
                  PDO_INTERPRETER: ${{ matrix.interpreter }}
              run: |
                  # The creation of a dummy branch is necessary for the CI tests
                  # to work on PRs. Based on empirical results, in the absence of
                  # this command, CI tests work on the main branch and on local
                  # branches. However, they fail as a PR is created.
                  git checkout -b ci-test-branch
                  . build/common-config.sh
                  make -C docker test

            - name: Generate SBOM
              uses: anchore/sbom-action@78fc58e266e87a38d4194b2137a3d4e9bcaf7ca1 # v0.14.3
              with:
                  image: pdo_client
                  output-file: build/sbom-spdx.json
